// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNlyGyL0q6QZ_xkfi9IoCBAcsmszFYAiw',
    appId: '1:776948573167:web:d34e48e3a43419224ccc1a',
    messagingSenderId: '776948573167',
    projectId: 'jnpt-note-book',
    authDomain: 'jnpt-note-book.firebaseapp.com',
    databaseURL: 'https://jnpt-note-book-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jnpt-note-book.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY2OJywDIOd7f3kimUpm9P5yxbLZyDNtU',
    appId: '1:776948573167:android:bfb6bcb2d226df604ccc1a',
    messagingSenderId: '776948573167',
    projectId: 'jnpt-note-book',
    databaseURL: 'https://jnpt-note-book-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jnpt-note-book.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNlyGyL0q6QZ_xkfi9IoCBAcsmszFYAiw',
    appId: '1:776948573167:web:c5a92128c87bdc214ccc1a',
    messagingSenderId: '776948573167',
    projectId: 'jnpt-note-book',
    authDomain: 'jnpt-note-book.firebaseapp.com',
    databaseURL: 'https://jnpt-note-book-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jnpt-note-book.appspot.com',
  );

}